### ISSUE TITLE
How to override $appbar-height?

### ISSUE THREAD

**Issue by julius-retzer** [react-toolbox/toolbox-loader#7]
I want to change the appbar-height and I figured the best way would be to change the variable. My theme.scss looks like this 

```
@import "~react-toolbox/lib/_globals";
$appbar-height: 3 * $unit !default;
```

but it doesn't change the height of the appbar. Thoughts? Thanks.

**Comment by javivelasco** [comment]
Yeah, I've just accepted a PR in toolbox repo because this variable had no `default` flag. Sorry! It will be available for the next release!
